Repository vedant1771/Hactoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#56 Added email slicer project code made by me
  Python/emailslicer.py
  about/anushka.txt
Labels: Hacktoberfest

#55 Vikas Ukani
  about/Vikas Ukani.txt
Labels: Hacktoberfest

#29 Update README.md
  README.md
Labels: Hacktoberfest

#30 Adding a Snake Game using Python
  Snake Game/Snake Game using python/README.md
  Snake Game/Snake Game using python/Snake_game.py
Labels: Hacktoberfest

#31 Create bellmenford.py
  bellmenford.py
Labels: Hacktoberfest

#32 Matrix Product
  Python/matrix.py
Labels: Hacktoberfest

#33 Added new python file
  text in handwriting/README.md
  text in handwriting/main.py
  text in handwriting/pywhatkit.png
Labels: Hacktoberfest

#34 Create Fibonacci.py
  Fibonacci.py
Labels: Hacktoberfest

#35 created toh.cpp
  toh.cpp
Labels: Hacktoberfest

#36 weighted mean.py
  weighted mean.py
Labels: Hacktoberfest

#37 Audiobook.py added to the file
  Python/Audio_book.py
Labels: Hacktoberfest

#38 Create helloworld.js
  Javascript/helloworld.js
Labels: Hacktoberfest

#40 add javascript function
  js/utils.js
Labels: Hacktoberfest

#41 Added Cyclic Sort in Java
  cyclicsort.java
Labels: Hacktoberfest

#42 Create calender.py
  calender.py
Labels: Hacktoberfest

#43 Added algorithm to calculate maximum subarray sum
  Python/Kadane_algorithm.py
Labels: Hacktoberfest

#45 Update Random.py
  Python/Random.py
Labels: Hacktoberfest

#47 insert_delete_circular_queue.py
  Python/insert_delete_circular_queue.py
Labels: Hacktoberfest

#48 Create Quicksort.py
  Python/Quicksort.py
Labels: Hacktoberfest

#49 Create primsalgo.cpp
  primsalgo.cpp
Labels: Hacktoberfest

#51 Some solutions done by me
  CPP/XXOORR.cpp
  JavaScript/Fibonacci_DP.js
Labels: Hacktoberfest

#52 DONE: Covid Data Fetching...
  Python/fetch_covid19.py
Labels: Hacktoberfest

#46 Update Readme.md
  README.md
Labels: Hacktoberfest

#54 Update Random.py
  Python/Random.py
Labels: Hacktoberfest

#61 Checking is anagram or not
  Python/is_anagram.py
Labels: Hacktoberfest

#62 Create a program Palindrome.c
  C/Palindrome.c
Labels: Hacktoberfest

#63 Create TridiagonalSystem.cpp
  C++/TridiagonalSystem.cpp
Labels: Hacktoberfest

#64 Add files via upload
  Python/remove list redundancy.py
Labels: Hacktoberfest

#65 Code to sort elements in an array using bubble sort method
  Python/bubble_sort.py
Labels: Hacktoberfest

#66 Finding Runner Up Score
  Python/Runner_up_score.py
Labels: Hacktoberfest

#67 Update Quicksort.py
  Python/Quicksort.py
Labels: Hacktoberfest

#68 Update Random.py
  Python/Random.py
Labels: Hacktoberfest

#69 prime no.,armstrong no.,palindrome string
  java/armstrong.java
  java/palindrome.java
  java/prime.java
  java/words.java
Labels: Hacktoberfest

#70 bubblesort.java
  bubblesort.java
  insertionsort.py
Labels: Hacktoberfest

#71 selectionsort.java
  Selectionsort.java
  linearsearch.py
Labels: Hacktoberfest

#72 binarysearch.java
  binarysearch.java
Labels: Hacktoberfest

#75 mergesort.c
  mergesort.c
Labels: Hacktoberfest

#76 selectionSort
  C/selectionSort.c
Labels: Hacktoberfest

#77 Create byte_alignment.cpp
  C++/byte_alignment.cpp
  HangGame.cpp
Labels: Hacktoberfest

#78 Add files via upload
  C/sum.c
Labels: Hacktoberfest

#79 Create Reverse string
  C++/Reverse string
Labels: Hacktoberfest

#80 Added cryptomachine program
  C++/Max_sum_contigous_array.cpp
  Python/cryptomachine.py
Labels: Hacktoberfest

#81 armstrong_number.c
  C/armstrong_number.c
Labels: Hacktoberfest

#82 Create primenumber.cpp
  primenumber.cpp
Labels: Hacktoberfest

#83 Add a new python file
  Python/fact_lambda.py
Labels: Hacktoberfest

#84 Create rat_and_maze.cpp
  rat_and_maze.cpp
Labels: Hacktoberfest

#85 Create Htrap.txt
  about/Htrap.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#86 Create MrUnknown.txt
  about/MrUnknown.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#87 Create heap.c
  C/heap.c
Labels: Hacktoberfest, hacktoberfest-accepted

#88 Create Htrap.txt
  about/Htrap.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#89 Create Temperature.c
  C/Temperature.c
Labels: Hacktoberfest, hacktoberfest-accepted

#90 Zigzagpattern_string.py
  Zigzagpattern_string.py
Labels: Hacktoberfest, hacktoberfest-accepted

#92 Add 01Knapsack Problem in C++
  C++/Dynamic Programing/01KnapsackProblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#94 improvised Search.py code
  Search.py
Labels: Hacktoberfest, hacktoberfest-accepted

#95 Added queue implementation in c language
  .vscode/c_cpp_properties.json
  C++/CatalanNo.cpp
  C/queue.c
Labels: Hacktoberfest, hacktoberfest-accepted

#96 calwithgui.py
  Python/calwithgui.py
  Python/numStrange.py
Labels: Hacktoberfest, hacktoberfest-accepted

#99 Hangman
  Python/hangman.py
  Python/hangmanwords.py
  Python/info.txt
  Python/logo.png
  info.txt
  logo.png
Labels: Hacktoberfest, hacktoberfest-accepted

#97 Maximum Length Subarray
  MaximumLengthSubarray.java
Labels: Hacktoberfest, hacktoberfest-accepted

#100 Linus pipe question
  Linus_pipe.c
Labels: Hacktoberfest, hacktoberfest-accepted

#101 added tic_tac_toe.py file
  C++/linear_search.cpp
  Python/tic_tac_toe.py
Labels: Hacktoberfest, hacktoberfest-accepted

#102 added gender identification by python
  bubble_sort.py
  text in handwriting/gender_recognition.py
Labels: Hacktoberfest, hacktoberfest-accepted

#103 password_generator
  Python/currency_convertor.py
  Python/password_generator.py
Labels: Hacktoberfest, hacktoberfest-accepted

#105 improvised linearsearch.py
  linearsearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#106 quickSort.c
  C/quickSort.c
Labels: Hacktoberfest, hacktoberfest-accepted

#107 Selfie using smile in python
  selfie_star/camera_click.wav
  selfie_star/haarcascade_frontalcatface.xml
  selfie_star/haarcascade_frontalface_default.xml
  selfie_star/haarcascade_smile.xml
  selfie_star/selfie_star.py
Labels: Hacktoberfest, hacktoberfest-accepted

#108 stack.c
  stack.c
Labels: Hacktoberfest, hacktoberfest-accepted

#109 Sequence weightage
  Sequence weightage
Labels: Hacktoberfest, hacktoberfest-accepted

#110 Create Fknapsack.cpp
  C++/Fknapsack.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#112 MATRIX ROTATION.C
  C/MATRIX ROTATION.C
Labels: Hacktoberfest, hacktoberfest-accepted

#113 Create Matrix rotation ack.c
  Matrix rotation ack.c
Labels: Hacktoberfest, hacktoberfest-accepted

#114 Helloworld with Cobra
  cobra/helloworld.cobra
  cobra/readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#115 added NQueenProblem.java
  java/NQueenProblem.java
Labels: Hacktoberfest, hacktoberfest-accepted

#117 Added mini web project that can be used to understand CSS styling better.
  miniprojectsWeb/cssSelector.html
Labels: Hacktoberfest, hacktoberfest-accepted

#118 Program to find transpose of matrix
  C++/matrix_transpose.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#119 added inheritance code in c++
  CPP/hello_world.cpp
  oops_inheritance.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#121 pieChart.py => a script which prints piechart
  Python/pieChart.py
Labels: Hacktoberfest, hacktoberfest-accepted

#122 calendar.py => a scripyt which prints calendar
  Python/calendar.py
Labels: Hacktoberfest, hacktoberfest-accepted

#123 speedtest.py => prints internet speed
  Python/speedtest.py
Labels: Hacktoberfest, hacktoberfest-accepted

#124 Added my python based sudoku solver
  Python/Sudoku.py
Labels: Hacktoberfest, hacktoberfest-accepted

#125 Create HeightCalculator.c
  C/HeightCalculator.c
Labels: Hacktoberfest, hacktoberfest-accepted

#126 Create oddeven.c
  C/oddeven.c
Labels: Hacktoberfest, hacktoberfest-accepted

#127 Create TimeSchedule.c
  C/TimeSchedule.c
Labels: Hacktoberfest, hacktoberfest-accepted

#128 Bubble sort
  C/Bubble sort.c
Labels: Hacktoberfest, hacktoberfest-accepted

#129 Stack
  C/stack_main.c
Labels: Hacktoberfest, hacktoberfest-accepted

#130 Circular_queue
  C/Circular_queue.c
Labels: Hacktoberfest, hacktoberfest-accepted

#131 Single Circular
  C/single_circular_ll.c
Labels: Hacktoberfest, hacktoberfest-accepted

#132 Create countDistinctElementUnorderedSet.cpp
  C++/countDistinctElementUnorderedSet.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#133 added min_maxElem_and_count_squares_problem_Solutions
  C++/Count_Squares.cpp
  C++/min_max_postn_of_elem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#134 Added PHP Codes
  PHP/php_control_statment.php
  PHP/php_datatypes.php
  PHP/php_operators.php
Labels: Hacktoberfest, hacktoberfest-accepted

#135 Added an code for binary no.
  binaryNo.java
Labels: Hacktoberfest, hacktoberfest-accepted

#137 Update Palindrome.c
  C/Palindrome.c
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#138 Created a program to find no of node present in LL
  linkedlist/countnode_in_linkdlist.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#139 Added Code to gui calc.py
  GUI calculator/gui calc.py
Labels: Hacktoberfest, hacktoberfest-accepted

#140 Create Convert a list of Tuples into Dictionary.py
  Python/Convert a list of Tuples into Dictionary.py
Labels: Hacktoberfest, hacktoberfest-accepted

#141 Added Go code
  Go/hello.go
  Go/linear_search.go
Labels: Hacktoberfest, hacktoberfest-accepted

#142 Update Random.py
  Python/Random.py
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#144 Update linearsearch.py
  linearsearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#145 Create kadane's_Algo.cpp
  kadane's_Algo.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#147 Create Queue.py
  Python/CircularQueue.py
  Python/queue.py
Labels: Hacktoberfest, hacktoberfest-accepted

#148 Update Sum of two matrix.py
  Python/Sum of two matrix.py
Labels: Hacktoberfest, hacktoberfest-accepted

#156 Add files via upload
  C/djikstra algo.c
  Python/GA(knapsack).py
Labels: Hacktoberfest, hacktoberfest-accepted

#157 Create Fibonacci.java
  Fibonacci.java
Labels: Hacktoberfest, hacktoberfest-accepted

#158 Optimised prime number code
  primenumber.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#160 Update Max_sum_contigous_array.cpp
  C++/Max_sum_contigous_array.cpp
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#162 Create Reduce_Row_Echelon_Form.java
  java/Reduce_Row_Echelon_Form.java
Labels: Hacktoberfest, hacktoberfest-accepted

#163 Create Binary,BubbleAndSelectionSort.cpp
  C++/Binary,BubbleAndSelectionSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#164 Create Josephus Circle
  C/Josephus Circle
Labels: Hacktoberfest, hacktoberfest-accepted

#165 added new question and solution
  C++/Dynamic Programing/Counting number of ways to cover a distance
Labels: Hacktoberfest, hacktoberfest-accepted

#166 multi.py
  multi.py
Labels: Hacktoberfest, hacktoberfest-accepted

#168 Add Pong Game in python
  Pong Game.py/ball.py
  Pong Game.py/paddle.py
  Pong Game.py/pong.py
  Pong Game.py/scoreboard.py
Labels: Hacktoberfest, hacktoberfest-accepted

#169 Branch1
  CPP/DFS.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#170 add a new file
  Python/linearsearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#172 LCS- Dynamic Prog
  C/LCS Problem
Labels: Hacktoberfest, hacktoberfest-accepted

#173 Create linuxmacchanger.py
  Python/linuxmacchanger.py
Labels: Hacktoberfest, hacktoberfest-accepted

#174 Added Tarjan's Algorithm
  Tarjan.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#175 Created parenclass.cpp
  C++/parentclass.Cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#177 Add files via upload
  Python/A-star Algorithm.py
Labels: Hacktoberfest, hacktoberfest-accepted

#178 Create Kadane_Algorithm.cpp
  C++/Kadane_Algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#179 Create EggDroppingProblem.cpp
  C++/Dynamic Programing/EggDroppingProblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#180 Print multiple hello World
  java/palindrome.java
Labels: Hacktoberfest, hacktoberfest-accepted

#181 Create guess the number.c
  guess the number.c
Labels: Hacktoberfest, hacktoberfest-accepted

#182 Create most_occurring_element.cpp
  C++/most_occuring_element.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#183 Create sizeofTree.cpp
  C++/sizeofTree.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#184 Create reverseString.py
  reverseString.py
Labels: Hacktoberfest, hacktoberfest-accepted

#185 Create Longest Arithematic Sub Array.cpp
  C++/Longest Arithematic Sub Array.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#186 Porfolio site
  banner.jpg
  index.html
  profile-1.jpeg
  profile-2.jpeg
  profile-3.jpeg
  profile-4.jpeg
  profile-5.jpeg
  script.js
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#187 Create LCS.cpp
  C++/Dynamic Programing/LCS.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#188 mono-alphabetic substitution cipher
  Python/mono-aplabetic-substitution.py
Labels: Hacktoberfest, hacktoberfest-accepted

#189 solve birthday problem
  C++/birthday.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#190 linked list using python
  Python/linked_list.py
Labels: Hacktoberfest, hacktoberfest-accepted

#191 Create Video to frames
  Video to Frames
Labels: Hacktoberfest, hacktoberfest-accepted

#192 Maximum of three numbers
  C++/Maximum of three numbers
Labels: Hacktoberfest, hacktoberfest-accepted

#193 Armstrong Number of three digits
  C/Armstrong Number of three digits.c
Labels: Hacktoberfest, hacktoberfest-accepted

#194 Code to find minimum and maximum element in an array
  max_min_element.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#197 Added a Currency Converter
  Python/currencyconverter.py
Labels: Hacktoberfest, hacktoberfest-accepted

#198 Create Palindrome_Checker.c
  Palindrome_Checker.c
Labels: Hacktoberfest, hacktoberfest-accepted

#199 k smallest
  java/kthSmallestElement.class
  java/kthSmallestElement.java
Labels: Hacktoberfest, hacktoberfest-accepted

#200 Binary Bucket Sort or 2-Radix sort
  Python/binary_bucket_sort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#201 Code of famous Riddle and DSA question
  C++/JosephusProblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#195 Create matrix_chain_multiplication
  matrix_chain_multiplication
Labels: Hacktoberfest, hacktoberfest-accepted

#202 Adding Drowsiness Detection college Project
  NewDrowsiness/DrowsinessDetector.py
  NewDrowsiness/alarm.wav
  NewDrowsiness/haarcascade_eye.xml
  NewDrowsiness/haarcascade_frontalface_default.xml
  NewDrowsiness/haarcascade_lefteye_2splits.xml
  NewDrowsiness/haarcascade_righteye_2splits.xml
Labels: Hacktoberfest, hacktoberfest-accepted

#203 Update Kadane_algorithm.py
  Python/Kadane_algorithm.py
Labels: Hacktoberfest, hacktoberfest-accepted

#207 Added Python Basics Program File
  Python/Python Basics.html
Labels: Hacktoberfest, hacktoberfest-accepted

#208 Added Wikipedia Search Application
  Python/Search_Application.py
Labels: Hacktoberfest, hacktoberfest-accepted

#209 sagar2002malik leap year check
  C/leapYear.c
Labels: Hacktoberfest, hacktoberfest-accepted

#210 added calculator which was implemented with python
  Python/calculator.py
Labels: Hacktoberfest, hacktoberfest-accepted

#212 MatrixMultiplicationinC++
  C++/MatrixMultiplicationC++
Labels: Hacktoberfest, hacktoberfest-accepted

#213 Create RotatedBinarySearch.java
  java/RotatedBinarySearch.java
Labels: Hacktoberfest, hacktoberfest-accepted

#214 Create medianof2sortedarrays.cpp
  medianof2sortedarrays.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#215 Sec
  Python/calender.py
  Python/qucksort.py
  bellmenford.py
Labels: Hacktoberfest, hacktoberfest-accepted
